spring:
  application:
    name: accounts
  profiles:
    active: production
  datasource:
    url: ${accounts.spring.datasource.url}
    username: ${accounts.spring.datasource.username}
    password: ${accounts.spring.datasource.password}
    jpa:
      database: ${accounts.spring.jpa.database}
      show-sql: ${accounts.spring.jpa.show-sql}
      hibernate:
        ddl-auto: ${accounts.spring.jpa.hibernate.ddl-auto}